"""
Borough-level Covasim calibration.

Fits each NYC borough separately against its own weekly deaths.
Defaults to fullest model (prog_by_age=1, sus_age_specific=1, pop_type=hybrid).
Supports all 4 configurations via CLI flags.

Usage:
    python agent_based_model_borough.py --borough BX --n_trials 10000 --n_jobs 8 --top_k 1000
    python agent_based_model_borough.py --borough NYC --prog_by_age 0 --sus_age_specific 0 --pop_type random --n_trials 10000

Borough codes: BX (Bronx), BK (Brooklyn), MN (Manhattan), QN (Queens), SI (Staten Island)

Requires:
    - Weekly deaths:  ../data/regions/NYC_{borough}/epidemic/weekly_deaths.csv
      (generated by preprocess_borough_deaths.py)
    - Age distribution: ../data/regions/NYC_{borough}/demographic/pop_age.csv
      (user must provide, same format as NYC/demographic/pop_age.csv)
    - Mobility data:  ../data/regions/NYC/restriction/all_reductions.csv
      (shared across all boroughs)
"""
import covasim as cv
import numpy as np
import pandas as pd
import optuna
import argparse
import os
import json
import time
import functools

print = functools.partial(print, flush=True)
optuna.logging.set_verbosity(optuna.logging.WARNING)

SIM_START = '2020-02-15'
FIT_START = '2020-03-15'
SIM_END   = '2020-07-05'

MOB_FILE = '../data/regions/NYC/restriction/all_reductions.csv'


def load_data(borough):
    if borough == 'NYC':
        # NYC total: use PEP 2019 data (consistent with borough data)
        pop_age_path = '../data/regions/NYC/demographic/pop_age_pep2019.csv'
        deaths_path = '../data/regions/NYC/epidemic/weekly_deaths.csv'
    else:
        pop_age_path = f'../data/regions/NYC_{borough}/demographic/pop_age.csv'
        deaths_path = f'../data/regions/NYC_{borough}/epidemic/weekly_deaths.csv'

    # --- age distribution ---
    pop_age = pd.read_csv(pop_age_path)
    # Expected format: age,population  (16 rows: 0-4, 5-9, ..., 75+)
    p = pop_age['population'].values

    p15 = int(p[15])  # 75+ group
    age_data = {
        '0-9':   int(p[0] + p[1]),
        '10-19': int(p[2] + p[3]),
        '20-29': int(p[4] + p[5]),
        '30-39': int(p[6] + p[7]),
        '40-49': int(p[8] + p[9]),
        '50-59': int(p[10] + p[11]),
        '60-69': int(p[12] + p[13]),
        '70-79': int(p[14]) + int(p15 * 5 / 15),
        '80+':   int(p15 * 10 / 15),
    }
    total_pop = sum(age_data.values())

    # --- weekly deaths ---
    deaths = pd.read_csv(deaths_path, parse_dates=['date'])
    deaths = deaths.set_index('date')['total']
    deaths = deaths[FIT_START:SIM_END]

    # --- mobility (shared NYC-wide) ---
    mob = pd.read_csv(MOB_FILE, parse_dates=['date'])
    mob = mob.set_index('date')['all_red']
    mob = mob[SIM_START:SIM_END]

    return age_data, total_pop, deaths, mob


# ---------- Covasim interventions (same as save_grouplevel) ----------

class FlatPrognoses(cv.Intervention):
    def initialize(self, sim):
        super().initialize()
        sim.people.symp_prob[:]   = sim.people.symp_prob.mean()
        sim.people.severe_prob[:] = sim.people.severe_prob.mean()
        sim.people.crit_prob[:]   = sim.people.crit_prob.mean()
        sim.people.death_prob[:]  = sim.people.death_prob.mean()
    def apply(self, sim):
        pass


class FlatSusceptibility(cv.Intervention):
    def initialize(self, sim):
        super().initialize()
        sim.people.rel_sus[:] = 1.0
    def apply(self, sim):
        sim.people.rel_sus[:] = 1.0


class MobilityIntervention(cv.Intervention):
    def __init__(self, mob):
        super().__init__()
        self.mob_dict  = {d.strftime('%Y-%m-%d'): v for d, v in mob.items()}
        self.orig_beta = None
    def initialize(self, sim):
        super().initialize()
        self.orig_beta = sim['beta']
    def apply(self, sim):
        date = sim.date(sim.t)
        if date in self.mob_dict:
            sim['beta'] = self.orig_beta * self.mob_dict[date]


# ---------- Simulation ----------

OUTPUT_AGE_GROUPS = {
    'age_0_17':  (0,  17),
    'age_18_24': (18, 24),
    'age_25_34': (25, 34),
    'age_35_44': (35, 44),
    'age_45_54': (45, 54),
    'age_55_64': (55, 64),
    'age_65_74': (65, 74),
    'age_75up':  (75, 150),
}


def run_sim(
    age_data,
    total_pop,
    mob,
    borough,
    prog_by_age      = True,
    sus_age_specific  = True,
    pop_type         = 'hybrid',
    beta             = 0.06,
    pop_infected     = 200,
    rel_death        = 0.5,
    pop_size         = 100e3,
    rand_seed        = 42,
):
    location_key = f'NYC_{borough}'
    cv.data.country_age_data.data[location_key] = age_data

    interventions = []
    if not prog_by_age:
        interventions.append(FlatPrognoses())
    if not sus_age_specific:
        interventions.append(FlatSusceptibility())
    interventions.append(MobilityIntervention(mob))

    pop_scale = total_pop / pop_size

    pars = dict(
        start_day      = SIM_START,
        end_day        = SIM_END,
        pop_size       = pop_size,
        pop_scale      = pop_scale,
        rescale        = True,
        pop_type       = pop_type,
        location       = location_key,
        beta           = beta,
        pop_infected   = pop_infected,
        rel_death_prob = rel_death,
        prog_by_age    = prog_by_age,
        rand_seed      = rand_seed,
        verbose        = 0,
    )

    sim = cv.Sim(pars=pars, interventions=interventions)
    return sim


def extract_age_group_deaths(sim):
    people    = sim.people
    n_days    = sim.npts
    pop_scale = sim['pop_scale']

    age_group_daily = {ag: np.zeros(n_days) for ag in OUTPUT_AGE_GROUPS}

    date_dead = people.date_dead
    ages      = people.age

    dead_mask = ~np.isnan(date_dead) & (date_dead >= 0) & (date_dead < n_days)
    dead_days = date_dead[dead_mask].astype(int)
    dead_ages = ages[dead_mask]

    for ag_name, (age_lo, age_hi) in OUTPUT_AGE_GROUPS.items():
        ag_mask = (dead_ages >= age_lo) & (dead_ages <= age_hi)
        if ag_mask.any():
            days_in_group = dead_days[ag_mask]
            counts = np.bincount(days_in_group, minlength=n_days)[:n_days]
            age_group_daily[ag_name] = counts.astype(float)

    for ag_name in age_group_daily:
        age_group_daily[ag_name] *= pop_scale

    return age_group_daily


# ---------- Calibration ----------

def calibrate(age_data, total_pop, mob, real_deaths, borough,
              prog_by_age, sus_age_specific, pop_type,
              n_trials=10000, n_jobs=16, top_k=1000):

    cal_start = time.time()

    def objective(trial):
        beta         = trial.suggest_float('beta',         0.01, 0.10)
        pop_infected = trial.suggest_int(  'pop_infected', 50,   500)
        rel_death    = trial.suggest_float('rel_death',    0.1,  1.0)

        sim = run_sim(
            age_data         = age_data,
            total_pop        = total_pop,
            mob              = mob,
            borough          = borough,
            prog_by_age      = prog_by_age,
            sus_age_specific = sus_age_specific,
            pop_type         = pop_type,
            beta             = beta,
            pop_infected     = pop_infected,
            rel_death        = rel_death,
        )
        sim.run()

        sim_daily = pd.Series(
            sim.results['new_deaths'].values,
            index=pd.to_datetime(sim.results['date']),
        )
        sim_weekly = sim_daily.resample('W').sum()
        sim_weekly = sim_weekly[FIT_START:]

        common_dates = real_deaths.index.intersection(sim_weekly.index)
        if len(common_dates) == 0:
            return 1e9

        loss = np.mean(
            (sim_weekly[common_dates].values - real_deaths[common_dates].values) ** 2
        )
        return loss

    def progress_callback(study, trial):
        n_done = trial.number + 1
        if n_done % 100 == 0 or n_done == 1:
            elapsed = time.time() - cal_start
            speed   = n_done / elapsed
            eta     = (n_trials - n_done) / speed if speed > 0 else float('inf')
            best    = study.best_value if study.best_trial else float('inf')
            print(f'  [Calibration] Trial {n_done:>6}/{n_trials} | '
                  f'this_loss={trial.value:.2f} | best={best:.2f} | '
                  f'{elapsed:.0f}s elapsed | ETA ~{eta:.0f}s | '
                  f'{speed:.1f} trials/s')

    study = optuna.create_study(direction='minimize')
    study.optimize(objective, n_trials=n_trials, n_jobs=n_jobs,
                   callbacks=[progress_callback])

    completed = [t for t in study.trials
                 if t.state == optuna.trial.TrialState.COMPLETE and t.value < 1e9]
    completed.sort(key=lambda t: t.value)
    top_trials = completed[:top_k]

    print(f'Completed trials: {len(completed)} / {n_trials}')
    print(f'Selected top {len(top_trials)} samples')

    return top_trials


def run_top_k_sims(top_trials, age_data, total_pop, mob, borough,
                   prog_by_age, sus_age_specific, pop_type):

    all_betas      = []
    all_popinf     = []
    all_rel_deaths = []
    all_losses     = []
    all_trajs      = []
    all_age_trajs  = {ag: [] for ag in OUTPUT_AGE_GROUPS}
    dates          = None
    t_start        = time.time()
    n_total        = len(top_trials)

    for i, trial in enumerate(top_trials):
        beta         = trial.params['beta']
        pop_infected = trial.params['pop_infected']
        rel_death    = trial.params['rel_death']
        loss         = trial.value

        sim = run_sim(
            age_data         = age_data,
            total_pop        = total_pop,
            mob              = mob,
            borough          = borough,
            prog_by_age      = prog_by_age,
            sus_age_specific = sus_age_specific,
            pop_type         = pop_type,
            beta             = beta,
            pop_infected     = pop_infected,
            rel_death        = rel_death,
            rand_seed        = 42,
        )
        sim.run()

        traj = sim.results['new_deaths'].values.copy()
        all_trajs.append(traj)

        ag_deaths = extract_age_group_deaths(sim)
        for ag in OUTPUT_AGE_GROUPS:
            all_age_trajs[ag].append(ag_deaths[ag])

        if dates is None:
            dates = np.array(sim.results['date'])

        all_betas.append(beta)
        all_popinf.append(pop_infected)
        all_rel_deaths.append(rel_death)
        all_losses.append(loss)

        if (i + 1) % 50 == 0 or (i + 1) == n_total:
            elapsed = time.time() - t_start
            speed   = (i + 1) / elapsed
            eta     = (n_total - i - 1) / speed if speed > 0 else 0
            print(f'  [Re-run] Sim {i+1:>5}/{n_total} | '
                  f'{elapsed:.0f}s elapsed | ETA ~{eta:.0f}s | '
                  f'{speed:.1f} sims/s')

    params_df = pd.DataFrame({
        'beta':         all_betas,
        'pop_infected': all_popinf,
        'rel_death':    all_rel_deaths,
    })
    loss_df = pd.DataFrame({'loss': all_losses})
    trajectories     = np.array(all_trajs)
    age_trajectories = {ag: np.array(all_age_trajs[ag]) for ag in OUTPUT_AGE_GROUPS}

    return params_df, loss_df, trajectories, age_trajectories, dates


# ---------- Main ----------

if __name__ == '__main__':

    parser = argparse.ArgumentParser()
    parser.add_argument('--borough', type=str, choices=['NYC', 'BX', 'BK', 'MN', 'QN', 'SI'], required=True,
                        help='NYC=whole city, BX=Bronx, BK=Brooklyn, MN=Manhattan, QN=Queens, SI=Staten Island')
    parser.add_argument('--n_trials', type=int, default=10000)
    parser.add_argument('--n_jobs',   type=int, default=8)
    parser.add_argument('--top_k',    type=int, default=1000)
    parser.add_argument('--outdir',   type=str, default='covasim_posteriors_borough')
    parser.add_argument('--prog_by_age',      type=int, choices=[0, 1], default=1)
    parser.add_argument('--sus_age_specific', type=int, choices=[0, 1], default=1)
    parser.add_argument('--pop_type',         type=str, choices=['hybrid', 'random'], default='hybrid')
    args = parser.parse_args()

    borough = args.borough

    prog_by_age      = bool(args.prog_by_age)
    sus_age_specific = bool(args.sus_age_specific)
    pop_type         = args.pop_type

    label = f'{borough}_prog{int(prog_by_age)}_sus{int(sus_age_specific)}_{pop_type}'

    print('=' * 60)
    print(f'Borough: {borough}')
    print(f'Configuration: prog_by_age={int(prog_by_age)}, sus_age_specific={int(sus_age_specific)}, pop_type={pop_type}')
    print(f'n_trials={args.n_trials}, n_jobs={args.n_jobs}, top_k={args.top_k}')
    print(f'Start time: {time.strftime("%Y-%m-%d %H:%M:%S")}')
    print('=' * 60)

    print('\n[Step 1/4] Loading data...')
    age_data, total_pop, real_deaths, mob = load_data(borough)
    print(f'  Borough: {borough}')
    print(f'  Population: {total_pop:,}')
    print(f'  Age distribution: {age_data}')
    print(f'  Death data points: {len(real_deaths)}')
    print(f'  Total observed deaths (fit window): {real_deaths.sum()}')
    print(f'  Mobility data points: {len(mob)}')

    print(f'\n[Step 2/4] Calibrating ({args.n_trials} trials, {args.n_jobs} jobs)...')
    t0 = time.time()
    top_trials = calibrate(
        age_data         = age_data,
        total_pop        = total_pop,
        mob              = mob,
        real_deaths      = real_deaths,
        borough          = borough,
        prog_by_age      = prog_by_age,
        sus_age_specific = sus_age_specific,
        pop_type         = pop_type,
        n_trials         = args.n_trials,
        n_jobs           = args.n_jobs,
        top_k            = args.top_k,
    )
    calib_time = time.time() - t0
    print(f'  Calibration done in {calib_time:.1f}s')
    print(f'  Best loss: {top_trials[0].value:.2f}')
    print(f'  Best beta: {top_trials[0].params["beta"]:.5f}')
    print(f'  Best pop_infected: {top_trials[0].params["pop_infected"]}')
    print(f'  Best rel_death: {top_trials[0].params["rel_death"]:.4f}')

    print(f'\n[Step 3/4] Re-running top {len(top_trials)} simulations...')
    t1 = time.time()
    params_df, loss_df, trajectories, age_trajectories, dates = run_top_k_sims(
        top_trials       = top_trials,
        age_data         = age_data,
        total_pop        = total_pop,
        mob              = mob,
        borough          = borough,
        prog_by_age      = prog_by_age,
        sus_age_specific = sus_age_specific,
        pop_type         = pop_type,
    )
    rerun_time = time.time() - t1
    print(f'  Re-run done in {rerun_time:.1f}s')

    print(f'\n[Step 4/4] Saving results...')
    os.makedirs(args.outdir, exist_ok=True)

    params_path = os.path.join(args.outdir, f'{label}_params.csv')
    params_df.to_csv(params_path, index=False)
    print(f'  Saved params:       {params_path}')

    loss_path = os.path.join(args.outdir, f'{label}_loss.csv')
    loss_df.to_csv(loss_path, index=False)
    print(f'  Saved loss:         {loss_path}')

    traj_path = os.path.join(args.outdir, f'{label}_trajectories.npz')
    np.savez_compressed(traj_path, trajectories=trajectories, dates=dates)
    print(f'  Saved trajectories: {traj_path}')

    age_traj_path = os.path.join(args.outdir, f'{label}_trajectories_by_age.npz')
    save_dict = {'dates': dates}
    for ag in OUTPUT_AGE_GROUPS:
        save_dict[f'deaths_{ag}'] = age_trajectories[ag]
    np.savez_compressed(age_traj_path, **save_dict)
    print(f'  Saved age-group trajectories: {age_traj_path}')

    summary = dict(
        borough           = borough,
        label             = label,
        config            = dict(
            prog_by_age      = prog_by_age,
            sus_age_specific = sus_age_specific,
            pop_type         = pop_type,
        ),
        total_pop         = total_pop,
        age_data          = age_data,
        n_trials          = args.n_trials,
        n_completed       = len(top_trials),
        top_k             = args.top_k,
        best_loss         = float(top_trials[0].value),
        best_beta         = float(top_trials[0].params['beta']),
        best_pop_infected = int(top_trials[0].params['pop_infected']),
        best_rel_death    = float(top_trials[0].params['rel_death']),
        calib_time_s      = round(calib_time, 1),
        rerun_time_s      = round(rerun_time, 1),
    )
    summary_path = os.path.join(args.outdir, f'{label}_summary.json')
    with open(summary_path, 'w') as f:
        json.dump(summary, f, indent=2)
    print(f'  Saved summary:      {summary_path}')

    total_time = time.time() - t0
    print('\n' + '=' * 60)
    print(f'All done! Total time: {total_time:.1f}s ({total_time/60:.1f} min)')
    print(f'End time: {time.strftime("%Y-%m-%d %H:%M:%S")}')
    print('=' * 60)
